### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by elsander**
I made a few small typo fixes/grammar changes in docx_add, docx_cursor, and the vignettes. Happy to split/change this PR if you want. If this is helpful, I can continue going through the documentation, but I didn't want to put too many line changes in one PR and make it too cumbersome.

### CODE REVIEW

**Comment by davidgohel** [comment]
thanks a lot, this really help users ... and I am learning from your correction :)

Just add yourself as contributor and I'll merge the request

**Comment by elsander** [comment]
Great, glad this is helpful! I really appreciate your work on this project, so I'm glad I can contribute. I just pushed a fix for the Travis build and added myself as a contributor, but GitHub is having some issues at the moment, so it may not show up right away.

**Comment by elsander** [comment]
Looks like the check failure here is because of test coverage-- I assume that the % coverage is going down because I added more lines of documentation. Do you want me to make any changes to make the check pass?

**Comment by davidgohel** [comment]
Oh, went too fast and missed your last comment. However I don't think that's important. 

Thanks for your help!

**Pull request merged**
