### PR TITLE
add pack_folder testing and body_add_img test

### PR DESCRIPTION
**Pull request by elsander**
When I was going through the code, I added a couple of tests. I don't think I have the expertise to write a thorough test suite like I'd hoped, but I thought I would open a PR in case you found these useful. Feel free to close if not.

### CODE REVIEW

**Comment by elsander** [comment]
It looks like the Travis build is failing, but it's related to a `sudo apt-get update` call, which my code shouldn't have affected. Not sure what's going on there.

**Comment by davidgohel** [comment]
Hi, thanks again!

Sorry, I am closing this one... but I copied 2 of the 3 updates :)

The last one should be more nasty but I will do it later. Also there is small issues (i.e. `mkdir` is system dependent)

**Comment by davidgohel** [comment]
for travis, it was not your code but travis ci...

**Comment by elsander** [comment]
Ah, good point abut `mkdir`. No problem about closing the ticket, and take whatever is useful!

**Pull request closed without merging**
