### PR TITLE
feat: add preserve parameter to `pptx_summary()` (#493)

### PR DESCRIPTION
**Pull request by elipousson**
As a follow-up to #500, I added the same functionality to `pptx_summary()`. Hope this is similarly welcome!

### CODE REVIEW

**Comment by elipousson** [comment]
I added a new test for this pull request and it looks like it now passes the automated checks. Let me know if there is anything else you wanted to see in this PR, @davidgohel.

**Comment by davidgohel** [comment]
Thanks. I will review it, but I can not dedicate time to it before long time. What I can tell you in a first look is to not use subset as adviced on its help page and to not use a variable name as you did in subset as I don't want to add them in globalVars. 

Run R CMD check and you will probably and you will probably be warned about that because of https://github.com/davidgohel/officer/pull/506/files#diff-8bc344faf5fca11ce90a5571589218e31372f6d3a9fd81ebcfed6f3085ad3e37R54

**Comment by elipousson** [comment]
Sure. I can adjust the test and no urgency to merge the request. I initially subset the row by position but I figured you'd want the style for the test to match the existing tests using subset.

**Comment by davidgohel** [comment]
Sorry for the yesterday comment, it's a small PR and I can review it quickly. 

Sorry also for not seeing the `subset` function was called inside a test and not inside a function of the package. 

Thanks for the time you dedicated to this

**Comment by elipousson** [comment]
No apologies needed. I belatedly realized the confusion when no alerts popped up on check. I'm a huge fan of the package and appreciate both your work and the need to set boundaries on your time!

**Pull request merged**
