### PR TITLE
Add option to preserve cell line breaks to `docx_summary()`

### PR DESCRIPTION
**Pull request by elipousson**
Following up on the feature request in #493, I went ahead and worked the preserve parameter into `docx_summary()`. The code is directly based on `docxtractr::docx_extract_tbl()` so, if you're interested in the pull request, I can also add Bob Rudis as a contributor for the package in the DESCRIPTION.

### CODE REVIEW

**Comment by davidgohel** [comment]
hello 

Can you share an example, I can not understand what is the use case it solves?

**Comment by elipousson** [comment]
The issue is when you are trying to use `docx_summary()` to extract data from a table where someone has used a list to organize text within a table cell. At present, the text from these two Word tables would appear to be identical in the data.frame returned by `docx_summary()`:

Table with a cell using a bulleted list

Table with a cell showing the same text collapsed into a single string

**Comment by davidgohel** [comment]
thanks,

I tried to create an example and it did not work.

[example.docx](https://github.com/davidgohel/officer/files/11521839/example.docx)

```
library(dplyr)
doc <- read_docx("example.docx")
docx_summary(doc) |> 
  filter(content_type %in% "table cell")
```

Capture d’écran 2023-05-20 à 09 55 35

Here are the two rows:

```
3.21         3   table cell Light Shading 2,46210657918,2034091    NA     NA      2     FALSE       3        2        1
1.3          5   table cell    Table Grid    This is 1This is 2    NA     NA      2     FALSE       1        1        1
```

**Comment by elipousson** [comment]
@davidgohel – just wanted to double-check my understanding of your comment: were you agreeing that the existing function "didn't work" to preserve line breaks? Or that the pull request didn't work to retain line breaks? Like I said in my last comment, I didn't change the existing default behavior but just wanted to make sure I understood everything clearly and provide whatever additional information may be helpful to review.

**Comment by davidgohel** [comment]
@elipousson no sorry, my bad, I forgot to set preserve to `TRUE`

**Comment by davidgohel** [comment]
everything is fine to me, I just tested and ran the check :) thank you!

**Comment by elipousson** [comment]
Awesome. Thank you! I'm excited to put this new functionality to work.

Incidentally, I've been developing an extension package called [officerExtras](https://elipousson.github.io/officerExtras/index.html). I'd welcome feedback if you have a chance to take a look at it. If you do and see anything that seems like it would be helpful to add back into officer, I'd be glad to contribute to the package again.

**Pull request merged**
