### PR TITLE
Update vignettes

### PR DESCRIPTION
**Pull request by jonmcalder**
- improve grammar
- improve consistency of spacing/code style
- reflow content to adhere to 80 character line limit where feasible

### CODE REVIEW

**Comment by davidgohel** [comment]
Thanks :) 

Why did you change my code style? Could you cancel that step?

**Comment by jonmcalder** [comment]
Apologies for the delayed response - somehow I missed your earlier comment.

For what it's worth I was not trying to change your code style. The spacing changes I made here were things that appeared inconsistent to me rather than intentional, and given that it's the vignettes and not pkg source code I thought it would be ok. Might have just been my preference for the [tidyverse style](http://style.tidyverse.org/) creeping in here though.

Happy to undo these.

**Comment by davidgohel** [comment]
> Might have just been my preference for the tidyverse style creeping in here though.

;) yes, that's what I was thinking. 

However, thanks. There are conflicts now, so let me do it by hand when I will have time (later).

**Comment by davidgohel** [comment]
Thank, I merged your modifications (on its way to cran).

**Pull request closed without merging**
