### PR TITLE
Add functionality to read and add DOCX comments

### PR DESCRIPTION
**Pull request by trekonom**
Hi David,

this PR proposes an approach to add the functionality to read and add comments to a Word document.

It adds new exported functions `run_comment` and `docx_comments` to add a comment to a run and to get comments as a  dataframe.  

Most of the code was adapted from the functions used to add footnotes and I merely did some renaming.

Here is an example of the new functionality:
``` r
library(officer)

fp_bold <- fp_text_lite(bold = TRUE)
fp_red <- fp_text_lite(color = "red")

bl <- block_list(
  fpar(ftext("Comment multiple words.", fp_bold)),
  fpar(ftext("Second line", fp_red))
)

a_par <- fpar(
  "This paragraph contains",
  run_comment(
    cmt = bl,
    run = ftext("a comment."),
    author = "Author Me",
    date = "2023-06-01"
  )
)

doc <- read_docx()
doc <- body_add_fpar(doc, value = a_par, style = "Normal")

docx_file <- print(doc, target = tempfile(fileext = ".docx"))

docx_comments(read_docx(docx_file))
#>   comment_id    author initials       date                                 text
#> 1          0 Author Me          2023-06-01 Comment multiple words., Second line
#>   commented_text
#> 1     a comment.
```

<sup>Created on 2023-06-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Hope you will find this useful. Let me know if you have any suggestions for changes.

Best, Stefan

### CODE REVIEW

**Comment by davidgohel** [comment]
hello and thanks (again). It's a cool new functionality and will probably be appreciated by many.

I will review it, but I will take time (not before 3 weeks at least) as I can not dedicate time on it for now (sorry).

**Comment by trekonom** [comment]
Thx for your reply. And sorry for my late one. No need to hurry. If I need the new functionality I can use it already. :D

**Comment by davidgohel** [comment]
Sorry for the delay, I finally did this review.

All seems perfect to me. Many thanks for this great PR.

**Comment by trekonom** [comment]
Thanks for your reply and the merge. I know from my own experience that - especially with a growing number of packages - maintaining a package takes time. (:

**Pull request merged**
