### PR TITLE
Add as.matrix.rpptx()

### LINKED ISSUE #403: Feature Request: as.matrix method for PowerPoint objects (rpptx)
I recently needed to extract the data from a table in a PowerPoint presentation.  I saw an example in the officeverse website suggesting that others have the same need (https://ardata-fr.github.io/officeverse/extract-content.html#powerpoint-tables).

For that, I think it would be useful to have an `as.matrix()` method for officer that could extract a specific table from a specific slide or all tables from all slides.  The rationale for doing all tables is that often, I wouldn't know what the ID number is.

Since I had the need, I have already created the function, and I'll submit a PR for it shortly.  And, if it's not of interest, then no worries to close the issue and PR.

### PR DESCRIPTION
**Pull request by billdenney**
Fix #403 

This adds an as.matrix.rpptx() function to extract tables from pptx files as matrices.

### CODE REVIEW

**Comment by davidgohel** [comment]
Thanks for the PR ; it works fine and it's complete (much appreciated!)

Could you add to your PR two minor changes?

* As a user, I'd like to have an `@examples` section, you can use this code if you want, it's based on an example file contained in the package:

```
#' @examples 
#' library(officer)
#' pptx_file <- system.file(package = "officer",
#'   "doc_examples", "example.pptx")
#' z <- read_pptx(pptx_file)
#' as.matrix(z, slide_id = NULL)
```

* could you add your details in `Authors@R` of `DESCRIPTION` file?

**Comment by billdenney** [comment]
Great!  I've added the suggested changes.

**Comment by davidgohel** [comment]
almost complete :) 

your role in DESCRIPTION is `ctb` and not `c("aut", "cre")`

**Comment by billdenney** [comment]
Whoops!  Mea culpa.  :)

**Comment by davidgohel** [comment]
thanks a lot

**Pull request merged**
