### PR TITLE
Add functionality to add speaker notes

### PR DESCRIPTION
**Pull request by beckni**
Hi,

I have implemented functionality that allows to add speaker nodes to slides. This had been requested before in #90. I hope you find the additions okay. Let me know if I can improve this somehow.

### CODE REVIEW

**Comment by davidgohel** [comment]
What a work! 

Please ping me back before the end of the week if I didn't review your code. Thanks, I appreciate a lot your contribution.

**Comment by davidgohel** [comment]
Thanks again, Here are my first comments:

### request for minor changes

#### rename `notes_ph*()`

Would you be ok to rename your functions?

* `notes_location_type()` instead of `notes_ph_type()`
* `notes_location_label()` instead of `notes_ph_label()`

It would use the same pattern than `ph_location_type()` and others 
placeholder location identifiers.

#### rename `add_notes()`

As notes can not be appended, I find it better to rename 
`add_notes()` to `set_notes()`.  

#### add an example 

Could you add an example to `add_notes()`, it would be 
good for the user to see what he can expect from the 
function.

#### credit

Could you add your name in the authors field of DESCRIPTION with role `ctb` 
and if possible in comment a short desc of what you did?

### Issue ?

I can't replace the content - I mean calling again `add_notes()`
does not replace the previous content. See following reprex:

```r
doc <- read_pptx()
doc <- add_slide(doc, "Title and Content", "Office Theme")
doc <- ph_with(x = doc, value = value,
               location = ph_location_type(type = "body"))
doc <- add_notes(doc, letters, notes_ph_type("body"))
doc <- add_notes(doc, "I am a test!", notes_ph_type("body"))
print(doc, target = "z.pptx")
```

**Comment by davidgohel** [comment]
Thank you, I think we can merge (the error that happens on macos-latest is not related)

**Comment by beckni** [comment]
Hi! Thanks for reviewing the code. I have renamed the functions as requested. It is your package after all. I have also added an example for `set_notes()` and added my name to the description file. The issue with replacing an existing note should be fixed now.

**Comment by davidgohel** [comment]
Yes, I tested and it worked. I have also tried to add `set_notes.fpar` and it worked well, we will be able to add fpar/block_list in the future without big efforts

**Pull request merged**
