### PR TITLE
Fix for issue #155

### LINKED ISSUE #155: Issue with Office version
Hi @davidgohel , I am facing an issue about officer and Office version on my computer. Indeed, when I try this code : 
```
library("officer")
library("dplyr")
doc <- read_docx() %>%
  body_add_par("Table 1") %>%
  body_add_par("", style = "Normal") %>%
  body_add_table(mtcars)

print(doc, target = "essai.docx")
```
I cannot open the exported document if I have Microsoft Office 2007 installed (I have an error message about problem detected in the document). However, I manage to open it if I install Microsoft Office 2016 instead. Is there something to adjust in the code to export document openable with Office 2007 ?

Here is my sessionInfo : 
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.6   officer_0.3.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     crayon_1.3.4     digest_0.6.16    assertthat_0.2.0 R6_2.2.2         magrittr_1.5    
 [7] pillar_1.3.0     zip_1.0.0        rlang_0.2.2      uuid_0.1-2       rstudioapi_0.7   bindrcpp_0.2.2  
[13] xml2_1.2.0       tools_3.5.1      glue_1.3.0       purrr_0.2.5      compiler_3.5.1   pkgconfig_2.0.2 
[19] base64enc_0.1-3  htmltools_0.3.6  tidyselect_0.2.4 bindr_0.1.1      tibble_1.4.2  
```
Thanks in advance !

### PR DESCRIPTION
**Pull request by vectorson**
Possibly fixes #155: Added a w:tblGrid inside w:tbl to comply with OOXML wml.xsd schema.

### CODE REVIEW

**Comment by vectorson** [comment]
Please be aware that this commit is untested. I based it solely on the schema. (http://www.datypic.com/sc/ooxml/e-w_tbl-1.html)

**Comment by davidgohel** [comment]
thanks @vectorson, it seems you saved me lot of time! 

You don't have Word 2007, do you? I'd like to test the result before merging...

**Comment by vectorson** [comment]
@davidgohel I have now added a commit that seems to have resolved the issue. I also reverted my first attempted fix (even though tblGrid should be there according to schema, "If it ain't broke, don't fix it.")

**Comment by davidgohel** [comment]
thanks @vectorson !

**Pull request merged**
