### PR TITLE
Add functionality to set shape geometry and outline

### PR DESCRIPTION
**Pull request by trekonom**
Hi David,

this PR adds the functionality to set the shape geometry and the outline. To this end I added two new arguments `geom` and `ln` to ´ph_location`. As an example the following reprex
```
library(officer)
doc <- read_pptx()
doc <- add_slide(doc)
loc <- ph_location(left = 1, top = 1, width = 4, height = 3, bg = "steelblue",
                   ln = sp_line(color = "red", lwd = 2.5),
                   geom = "trapezoid")
doc <- ph_with(doc, "", loc = loc)
print(doc, target = tempfile(fileext = ".pptx") )
```
will add a shape with a trapezoid geometry and a red outline.

Besides some helper functions to add the OOXML code I added two new functions `sp_line` and `sp_lineend` which in the spirit of the `fp***` family of functions could be used to set the properties of a (out)line.

**Background**: My company has a slide library including more than 150 slides which make heavy use of shapes with different geometries and outlines. However, adapting the examples always requires some or a lot of manual work (e.g. if you need only 3 of the 4 shapes offered by default). Also, as I aim to automate the creation of slide decks, adding slides manually will break reproducibility and will diminish the benefit of creating slide decks automatically.

I'm not aware of any issue which requested this feature. But I hope you (and others) will find these additions useful. Let me know if I can improve this somehow.

### CODE REVIEW

**Comment by davidgohel** [comment]
Hello Stephan

It's a very welcome contribution, I did not look at the code in detail, but it looks good. I will review it but have no time available for now. I will try next week. 

David

**Comment by trekonom** [comment]
Hej David,
thanks for your reply. Sounds great. Contact me when you've got the time to review my code.
Best S.

**Comment by davidgohel** [comment]
Hi, 

I finally took time to review your PR. Sorry for the time it took. 

It looks good to me, I don't have any request!

If you don't mind, I will add your name as contributor.

Many thanks,
David

**Comment by trekonom** [comment]
Hi David,
thanks for you reply and for reviewing the PR. Sounds great.

Would be a pleasure to be added as a contributor to the `officer` package.

Thanks for all your great work which makes my life so much easier :)

Stefan

**Pull request merged**
